---
title: "function-making-rasters"
format: html
---

```{r}
#|ouput: false

library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(patchwork)
```

```{r}
#|ouput: false

magpie <- read_csv(here::here("week7", "discussion","data", "magpie_obvs.csv"))
tule_elk <- read_csv(here::here("week7", "discussion", "data", "tule_elk_obvs.csv"))

bioclim_dir <- here::here("week7", "discussion", "data", "climate", "wc2.1_2.5m")
bioclim <- list.files(bioclim_dir, pattern = glob2rx("*.tif$"), full.names = TRUE)
bioclim_sort <- bioclim[
  # Sort filepaths based on numeric suffix
  order(
    # Extract numeric suffix of filenames and convert to numeric
    as.numeric(gsub(".*_(\\d+)\\.tif$", "\\1", bioclim))
    )
  ]
bioclim_rast <- rast(bioclim_sort)
```
### Name raster layers
```{r}
variables <- c("annualMeanTemp", "meanDiurnalRange", "isothermality", "tempSeasonality", "maxTempWarmMonth", "maxTempColdMonth", "tempAnnualRange", "meanTempWetQ", "meanTempDryQ", "meanTempWarmQ", "meanTempColdQ", "annualPrecip", "precipWetMonth", "precipDryMonth", "precipSeasonality", "precipWetQ", "precipDryQ", "precipWarmQ", "precipColdQ")
names(bioclim_rast) <- variables
```

### Find geographic extent of species occurrence and crop raster
```{r}
magpie_sf <- magpie |> 
  rename(long = longitude,
         lat = latitude) |> 
  drop_na(long, lat) |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

# find the extent of the species occurrence
magpie_bbox <- st_bbox(magpie_sf)

bioclim_crop <- crop(bioclim_rast, magpie_bbox)
```

### Extract points from species occurences
```{r}
bioclim_pts <- as_tibble(terra::extract(bioclim_crop, magpie_sf))
```

### Create background values and extract points
```{r}
# generate random sample points from raster
random_pts <- terra::spatSample(bioclim_crop[["annualMeanTemp"]],
                         na.rm = TRUE, # random sample non-NA cells
                         size = (nrow(magpie) * 2), # sample size
                         as.points = TRUE) |> # return SpatVector
  st_as_sf()

# Extract points from raster for background values
bioClim_random_pts <- as_tibble(terra::extract(bioclim_crop, random_pts))
```

### Plot species climate niche
```{r}
map_1 <- tm_shape(bioclim_crop[["annualPrecip"]]) +
  tm_raster(col.scale = tm_scale_continuous(values = "Blues"), 
            col.legend = tm_legend(title = "Annual precipitation")) +
  tm_shape(magpie_sf) +
  tm_dots(fill = "#3a5a40", size = 0.15) +
  tm_layout(legend.position = tm_pos_in("center", "bottom"),
            legend.orientation = "landscape",
            legend.bg.color = "white")

map_2 <- tm_shape(bioclim_crop[["annualMeanTemp"]]) +
  tm_raster(col.scale = tm_scale_continuous(values = "-RdYlBu"), 
            col.legend = tm_legend(title = "Annual mean temperature")) +
  tm_shape(magpie_sf) +
  tm_dots(fill = "#3a5a40", size = 0.15) +
  tm_layout(legend.position = tm_pos_in("center", "bottom"),
            legend.orientation = "landscape",
            legend.bg.color = "white")

tmap_arrange(map_1, map_2)
```

```{r}
plot_1 <- ggplot(data = bioclim_pts, aes(x = annualPrecip, y = annualMeanTemp)) +
  geom_point(shape = 16, color = "#3a5a40") +
  labs(x = "Annual precipitation",
       y = "Annual mean temperature", 
       title = "Species climate niche") +
  theme_bw()

plot_2 <- ggplot(data = bioClim_random_pts, aes(x = annualPrecip, y = annualMeanTemp)) +
  geom_point(shape = 16, color = "#1F1A38", alpha = 0.5) +
  labs(x = "Annual precipitation",
       y = element_blank(), 
       title = "Background climate") +
  theme_bw()

plot_1 + plot_2
```

